services:
  postgres-db:
    image: postgres:15
    container_name: pet-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}      # основной пользователь (например, postgres)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # хост:контейнер
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${AUTH_DB_NAME}
      DB_USER: ${AUTH_DB_USER}
      DB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./logs:/app/logs

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${USER_DB_NAME}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: